version: '2'
services:
  micro-sender:
    container_name: micro-sender1
    build:
      dockerfile: Dockerfile
    image: micro-sender:latest
    ports:
      - 8080:8080
    networks:
      - sender
  micro-recipient:
    container_name: micro-recipient1
    build:
      dockerfile: Dockerfile
    image: micro-recipient:latest
    ports:
      - 8800:8800
    networks:
      - recipient
    links:
      - rabbitmq
  micro-collector:
    container_name: micro-collector1
    build:
      dockerfile: Dockerfile
    image: micro-collector:latest
    ports:
      - 9000:9000
    networks:
      - recipient
    links:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - recipient
      - sender
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ${pwd}\prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - sender
  grafana:
    image: grafana/grafana:latest
    volumes:
       - ${pwd}\grafana.ini:/etc/grafana/grafana.ini
       - ${pwd}\datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    links:
      - prometheus
    networks:
      - sender

networks:
  recipient:
    driver: bridge
  sender:
    driver: bridge